export const EXTENTIONICONS = {
  'cast_aip_souce':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.aip.png',
  'angularjs':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.angularjs.png',
  'cfamily':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.cfamily.png',
  'egl':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.egl.png',
  'flex':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.flex.png',
  'fortran':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.fortran.png',
  'rpg':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.rpg.png',
  'sapui5':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.sapui5.png',
  'nodejs':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.nodejs.png',
  'nosqldotnet':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.nosqldotnet.png',
  'dotnet':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.dotnet.png',
  'html5':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.html5.png',
  'jquery':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.jquery.png',
  'tibco':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.tibco.png',
  'php':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.php.png',
  'siebel':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.siebel.png',
  'greenit':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.green-software.png',
  'systemlevelrules':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.systemlevelrules.png',
  'sqlanalyzer':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.sqlanalyzer.png',
  'jee':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.jee.png',
  'xset':'https://raw.githubusercontent.com/CAST-Extend/resources/master/technologyplaceholder.png',
  'pl1':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.pli.png',
  'python':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.python.png',
  'shell':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.shell.png',
  'peoplesoft':'https://raw.githubusercontent.com/CAST-Extend/resources/master/com.castsoftware.peoplesoft.png',

};
