module.exports = {
  QualityStandard: require("./quality-standard"),
  BaseQualityStandard: require("./base-quality-standard"),
  QualityStandardItem: require("./quality-standard-item"),
  QualityStandardCategory: require("./quality-standard-category"),
  QualityRuleReference: require("./quality-rule-reference"),
  QualityTemplateReference: require("./quality-template-reference"),
  QualityRule: require("./quality-rule"),
  QualityStandardItemReference: require("./quality-standard-item-reference"),
  BaseExtension: require("./base-extension"),
  ExtensionVersion: require("./extension-version"),
  Extension: require("./extension"),
  BaseBusinessCriteria: require("./base-business-criteria"),
  BusinessCriteria: require("./business-criteria"),
  TechnicalCriteriaReference: require("./technical-criteria-reference"),
  TechnicalCriteria: require("./technical-criteria"),
  ServiceIndex: require("./service-index"),
};