export const TECHNOLOGY = 'TECHNOLOGY';
export const BUSINESSCRITERIA = 'BUSINESSCRITERIA';
export const EXTENTION = 'EXTENTION';
export const QUALITYSTANDARD = 'QUALITYSTANDARD';
export const CASTAIP = 'CASTAIP';