module.exports = {
  ApiController: require("./api-controller"),
  QualityRulesController: require("./quality-rules-controller"),
  SwaggerUIController: require("./swagger-ui-controller"),
  StaticRestController: require("./static-rest-controller"),
  StaticRestUIController: require("./static-rest-ui-controller"),
  AIPServiceController: require("./aip-service-controller"),
  CARLServiceController: require("./carl-service-controller"),
  BaseServiceController: require("./base-service-controller"),
  TechnologyController: require("./technology-controller"),
  QualityStandardController: require("./quality-standard-controller"),
  ExtensionController: require("./extension-controller"),
  BusinessCriteriaController: require("./business-criteria-controller"),
  IndexController: require("./index-controller"),
  TechnicalCriteriaController: require("./technical-criteria-controller"),
  SSOController: require("./sso-controller"),
  PublicController: require("./public-controller"),
  RulesController: require("./rules-controller"),
};