export const EXTENTIONNAMES = {
  'CAST AIP': 'CAST AIP',
  'angularjs':'Angular JS Analyzer',
  'cfamily':'Objective-C Analyzer',
  'egl':'EGL Analyzer',
  'flex':'FLEX Analyzer',
  'fortran':'Fortran Analyzer',
  'rpg':'RPG Analyzer',
  'sapui5':'SAP UI 5 Analyzer',
  'nodejs':'Node JS Analyzer',
  'nosqldotnet':'NoSQL .NET Analyzer',
  'dotnet':'.NET Analyzer',
  'html5':'HTML5 Analyzer',
  'jquery':'jQuery Analyzer',
  'tibco':'Tibco Analyzer',
  'php':'PHP Analyzer',
  'siebel':'Siebel Analyzer',
  'greenit':'GreenIT Analyzer',
  'systemlevelrules':'System Level Rules',
  'sqlanalyzer':'SQL Analyzer',
  'jee': 'JEE Analyzer',
  'xset':'XSET Analyzer',
  'pl1':'PL1 Analyzer',
  'python':'Python Analyzer',
  'shell':'Shell Analyzer',
  'peoplesoft':'PeopleSoft Analyzer',
  'cpp': 'C/C++',
  'wbslinker': 'Web Services',
  'nosqljava': 'NoSQL Analyzer',
  'jeerules': 'JEE Rules',
  springsecurity: 'Spring Security',
  typescript: 'TypeScript Analyzer'
};