module.exports = {
  aip: "AIP",
  carl: "CARL",
  businessCriteria: "business-criteria",
  extensions: "extensions",
  qualityRules: "quality-rules",
  qualityTemplates: "quality-templates",
  qualityStandards: "quality-standards",
  technicalCriteria: "technical-criteria",
  technologies: "technologies",
  versions: "versions",
  categories: "categories",
  items: "items",
  aipId: "com.castsoftware.aip",
};